export const CADASTRO_ALUNO_SUCCESS = 'CADASTRO_ALUNO_SUCCESS';
export const CADASTRO_ALUNO_REQUEST = 'CADASTRO_ALUNO_REQUEST';
export const CADASTRO_ALUNO_FAILURE = 'CADASTRO_ALUNO_FAILURE';


export const UPDATE_ALUNO_SUCCESS = 'UPDATE_ALUNO_SUCCESS';
export const UPDATE_ALUNO_REQUEST = 'UPDATE_ALUNO_REQUEST';
export const UPDATE_ALUNO_FAILURE = 'UPDATE_ALUNO_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';


export const PERSIST_REHYDRATE = 'persist/REHYDRATE'